### ISSUE TITLE
fix gulp build on latest node

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/rooibos#83]
the gulp build fails with this error on the latest stable version of node:

```
▶ nvm use stable
Now using node v13.6.0 (npm v6.13.4)
npm install
  /tmp/rooibos     master   
▶ npx gulp dist     
[16:45:10] Requiring external module ts-node/register
[16:45:11] Using gulpfile /tmp/rooibos/gulpfile.ts
[16:45:11] Starting 'dist'...
[16:45:11] Starting 'clean'...
Doing a clean at dist/**
[16:45:11] Finished 'clean' after 14 ms
[16:45:11] Starting 'createDirectories'...
[16:45:11] Finished 'createDirectories' after 21 ms
[16:45:11] Starting 'compile'...
parsing config {
  filePattern: [ '**/*.bs', '**/*.brs', '**/*.xml' ],
  sourcePath: 'src',
  outputPath: 'build',
  logLevel: 4,
  nonCheckedImports: []
}
config does not specify processingExcludedPathsusing default value [
  '!components/rLogComponents/**/*.*',
  '!source/rLog/**/*.*',
  '!source/tests/rooibosDist.brs',
  '!source/tests/rooibosFunctionMap.brs'
]
Please read the docs for usage details https://github.com/georgejecook/maestro/blob/master/docs/index.md#maestro-cli
Processor is working with config {
  filePattern: [ '**/*.bs', '**/*.brs', '**/*.xml' ],
  sourcePath: 'src',
  outputPath: 'build',
  logLevel: 4,
  nonCheckedImports: [],
  processingExcludedPaths: null
}
processingExcludedPaths:: 0.071ms
filePattern:: 15.712ms
parents:: 0.185ms

Complete

[16:45:11] Finished 'compile' after 36 ms
[16:45:11] Starting 'insertVersionNumber'...
[16:45:11] Finished 'insertVersionNumber' after 429 μs
[16:45:11] Starting 'squash'...
[16:45:11] Finished 'squash' after 30 ms
[16:45:11] Starting 'copyToSamples'...
[16:45:11] Finished 'copyToSamples' after 456 μs
[16:45:11] Starting 'copyToTests'...
[16:45:11] Finished 'copyToTests' after 365 μs
[16:45:11] Starting 'doc'...
[16:45:11] 'doc' errored after 53 ms
[16:45:11] Error: exited with error code: 1
    at ChildProcess.onexit (/tmp/rooibos/node_modules/end-of-stream/index.js:39:36)
    at ChildProcess.emit (events.js:321:20)
    at ChildProcess.EventEmitter.emit (domain.js:547:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
[16:45:11] 'dist' errored after 159 ms

...

```

**Comment by georgejecook** [comment]
resolved
